# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Describe An Arrow Schema
#'
#' @param ptr An external pointer object for an \code{ArrowSchema} structure
#' @return None. The function is invoked for the side effect of display schema info.
describeArrowSchema <- function(ptr) {
    invisible(.Call(`_RcppArrow_describeArrowSchema`, ptr))
}

#' Describe An Arrow Array
#'
#' @param ptr An external pointer object for an \code{ArrowArray} structure
#' @return None. The function is invoked for the side effect of display schema info.
describeArrowArray <- function(ptr) {
    invisible(.Call(`_RcppArrow_describeArrowArray`, ptr))
}

#' Count Null Elements in Arrow Object
#'
#' @param array_data_xptr An external pointer to an Arrow object
#' @return The number of null elements
#' @examples
#' extract_null_count(narrow::as_narrow_array(c(NA, NA, 1:5))$array_data)
extract_null_count <- function(array_data_xptr) {
    .Call(`_RcppArrow_extract_null_count`, array_data_xptr)
}

