# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call array info
#'
#' @param adptr An external pointer to array data object
#' @return A list with array info
#' @examples
#' if (requireNamespace("narrow", quietly=TRUE)) {
#'     x <- narrow::as_narrow_array(c(NA, 2, NA, 4:7))
#'     narrow_array_info(x$array_data)
#' }
narrow_array_info <- function(adptr) {
    .Call(`_RcppArrow_narrow_array_info`, adptr)
}

#' Describe An Arrow Schema
#'
#' @param ptr An external pointer object for an \code{ArrowSchema} structure
#' @return None. The function is invoked for the side effect of displaying the
#' schema info.
describeArrowSchema <- function(ptr) {
    invisible(.Call(`_RcppArrow_describeArrowSchema`, ptr))
}

#' Describe An Arrow Array
#'
#' @param ptr An external pointer object for an \code{ArrowArray} structure
#' @return None. The function is invoked for the side effect of displaingy some
#' array info.
describeArrowArray <- function(ptr) {
    invisible(.Call(`_RcppArrow_describeArrowArray`, ptr))
}

#' Print uint64_t vector
#'
#' @param ptr An external pointer object for an \code{uint64_t} vector
#' @return None. The function is invoked for the side effect of display schema info.
print_uint64 <- function(ptr) {
    invisible(.Call(`_RcppArrow_print_uint64`, ptr))
}

#' Count Null Elements in Arrow Object
#'
#' @param array_data_xptr An external pointer to an Arrow object
#' @return The number of null elements
#' @examples
#' if (requireNamespace("narrow", quietly=TRUE)) {
#'     extract_null_count(narrow::as_narrow_array(c(NA, NA, 1:5))$array_data)
#' }
extract_null_count <- function(array_data_xptr) {
    .Call(`_RcppArrow_extract_null_count`, array_data_xptr)
}

